// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.update.auto.migrated", true);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1605923577);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("app.update.migrated.updateDir2.308046B0AF4A39CB", true);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.viewableInternally.typeWasRegistered.svg", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.xml", true);
user_pref("browser.launcherProcess.enabled", true);
user_pref("browser.migration.version", 102);
user_pref("browser.newtabpage.activity-stream.impressionId", "{f636b91a-66e4-487e-b2b6-13215e6aa3c2}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"shareURL\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1605923556914");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1605945156914");
user_pref("browser.search.region", "CH");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20201112153044");
user_pref("browser.shell.didSkipDefaultBrowserCheckOnFirstRun", true);
user_pref("browser.slowStartup.averageTime", 8577);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20201112153044");
user_pref("browser.startup.homepage_override.mstone", "83.0");
user_pref("browser.startup.lastColdStartupCheck", 1605923549);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1605923551737");
user_pref("distribution.iniFile.exists.appversion", "83.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("dom.push.userAgentID", "4fb9564122ad420ca33a32f667400c26");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 33);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "83.0");
user_pref("extensions.lastPlatformVersion", "83.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_picture_in_picture_overrides", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"3ca2c0f8-d81f-4846-a9bd-478379c8f018\",\"formautofill@mozilla.org\":\"65593282-27fc-4992-9db5-bd3eec03b724\",\"screenshots@mozilla.org\":\"e6a44ea6-e4f9-454d-92b0-6db5a1726ce1\",\"webcompat-reporter@mozilla.org\":\"0f1fcd4c-5b91-4598-bf8e-b59a0b19ea88\",\"webcompat@mozilla.org\":\"625a48e7-03ec-4a82-a62c-0d3735744efd\",\"default-theme@mozilla.org\":\"544ef810-dc83-4538-9d2c-ccb5417b4676\",\"google@search.mozilla.org\":\"d96868da-f7c3-422c-9ca4-2e3bd4662e39\",\"amazondotcom@search.mozilla.org\":\"3bf88036-5935-4796-903c-79f94f4cf9d8\",\"wikipedia@search.mozilla.org\":\"92f4c080-c8f5-4004-8553-fb706d864f4f\",\"bing@search.mozilla.org\":\"2fa3c521-bcbc-4b22-9d5c-95a5f1e36e2b\",\"ddg@search.mozilla.org\":\"d82c7c32-2283-49d7-a178-23662ed3176e\",\"ebay@search.mozilla.org\":\"379c55d2-c229-4515-a30e-281ed87f312d\"}");
user_pref("gfx-shader-check.build-version", "20201112153044");
user_pref("gfx-shader-check.device-id", "0x0166");
user_pref("gfx-shader-check.driver-version", "10.18.10.4358");
user_pref("gfx.crash-guard.status.wmfvpxvideo", 2);
user_pref("gfx.crash-guard.wmfvpxvideo.appVersion", "83.0");
user_pref("gfx.crash-guard.wmfvpxvideo.deviceID", "0x0166");
user_pref("gfx.crash-guard.wmfvpxvideo.driverVersion", "10.18.10.4358");
user_pref("layers.mlgpu.sanity-test-failed", true);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x0166");
user_pref("sanity-test.driver-version", "10.18.10.4358");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20201112153044");
user_pref("sanity-test.webrender.force-disabled", false);
user_pref("security.sandbox.content.tempDirSuffix", "{102ae1fd-7f02-46fa-939c-ebc4f750b2e3}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{f7ab24eb-4a95-43c4-b02c-bcbf6e015257}");
user_pref("signon.usage.hasEntry", false);
user_pref("toolkit.startup.last_success", 1605923540);
user_pref("toolkit.telemetry.cachedClientID", "53026f4a-343b-4dba-a7da-d4b5e2767b74");
user_pref("toolkit.telemetry.previousBuildID", "20201112153044");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
